version: '3'

services:
  quadrant-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quadrant-tool
    restart: always
    ports:
      - "8080:80"
    networks:
      - quadrant-network

networks:
  quadrant-network:
    driver: bridge